# Generated by Django 4.0.4 on 2022-05-03 14:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.IntegerField(blank=True, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('invoice_id', models.UUIDField(default=uuid.uuid5, primary_key=True, serialize=False, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_name', models.CharField(max_length=200)),
                ('item_quantity', models.IntegerField()),
                ('item_price', models.IntegerField()),
                ('item_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.invoice')),
            ],
        ),
    ]
