# Generated by Django 4.0.4 on 2022-05-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0004_alter_invoice_options_alter_items_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoiceapp.invoice'),
        ),
    ]
