# Generated by Django 4.0.4 on 2022-05-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0005_alter_items_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Name'),
        ),
    ]
